<?php
/**
 * Template Name: Article & Resource Page
 *
 * Clean reading experience with sidebar for articles and resource pages
 *
 * @package iHowz
 * @since 1.0.0
 */

get_header(); ?>

<main id="primary" class="site-main template-article">

    <div class="container">
        <div class="article-layout">

            <!-- Main Article Content -->
            <article class="article-content">
                <?php while (have_posts()) : the_post(); ?>

                <header class="article-header">
                    <h1 class="article-title"><?php the_title(); ?></h1>

                    <div class="article-meta">
                        <span class="author"><?php _e('By', 'ihowz-theme'); ?> <?php the_author(); ?></span>
                        <span class="date"><?php echo get_the_date(); ?></span>
                        <?php
                        $reading_time = get_field('reading_time');
                        if ($reading_time) : ?>
                            <span class="reading-time"><?php echo esc_html($reading_time); ?> <?php _e('min read', 'ihowz-theme'); ?></span>
                        <?php endif; ?>
                    </div>

                    <!-- Share Buttons -->
                    <div class="share-buttons">
                        <span><?php _e('Share:', 'ihowz-theme'); ?></span>
                        <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode(get_permalink()); ?>" target="_blank" rel="noopener" class="share-btn facebook"><?php _e('Facebook', 'ihowz-theme'); ?></a>
                        <a href="https://twitter.com/intent/tweet?url=<?php echo urlencode(get_permalink()); ?>&text=<?php echo urlencode(get_the_title()); ?>" target="_blank" rel="noopener" class="share-btn twitter"><?php _e('Twitter', 'ihowz-theme'); ?></a>
                        <a href="https://www.linkedin.com/sharing/share-offsite/?url=<?php echo urlencode(get_permalink()); ?>" target="_blank" rel="noopener" class="share-btn linkedin"><?php _e('LinkedIn', 'ihowz-theme'); ?></a>
                    </div>

                    <!-- Article Summary/TLDR -->
                    <?php
                    $article_summary = get_field('article_summary');
                    if ($article_summary) : ?>
                    <div class="article-summary">
                        <h3><?php _e('Summary', 'ihowz-theme'); ?></h3>
                        <?php echo wpautop($article_summary); ?>
                    </div>
                    <?php endif; ?>
                </header>

                <!-- Main Content -->
                <div class="article-main-content">
                    <?php the_content(); ?>
                </div>

                <!-- Member-Only Section CTA -->
                <?php if (get_field('has_member_content')) : ?>
                <div class="member-only-cta">
                    <h3><?php _e('Want Full Access?', 'ihowz-theme'); ?></h3>
                    <p><?php _e('Join today to unlock exclusive member-only content, resources, and support.', 'ihowz-theme'); ?></p>
                    <a href="<?php echo esc_url(get_permalink(get_page_by_path('join'))); ?>" class="btn btn-cta"><?php _e('Join for Full Access', 'ihowz-theme'); ?></a>
                </div>
                <?php endif; ?>

                <!-- Downloadable Resources -->
                <?php
                $resources = get_field('downloadable_resources');
                if ($resources) : ?>
                <div class="downloadable-resources">
                    <h3><?php _e('Downloadable Resources', 'ihowz-theme'); ?></h3>
                    <ul class="resource-list">
                        <?php foreach ($resources as $resource) : ?>
                        <li>
                            <a href="<?php echo esc_url($resource['file']['url']); ?>" class="resource-link" download>
                                <?php echo esc_html($resource['title']); ?>
                                <span class="file-type"><?php echo strtoupper(pathinfo($resource['file']['filename'], PATHINFO_EXTENSION)); ?></span>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php endif; ?>

                <?php endwhile; ?>
            </article>

            <!-- Sidebar -->
            <aside class="article-sidebar">
                <!-- Table of Contents -->
                <div class="sidebar-widget toc-widget">
                    <h3><?php _e('Table of Contents', 'ihowz-theme'); ?></h3>
                    <div id="table-of-contents">
                        <!-- Will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Sidebar Ads - Medium Rectangle -->
                <?php if (is_active_sidebar('article-sidebar-top')) : ?>
                <div class="sidebar-widget ad-widget">
                    <?php dynamic_sidebar('article-sidebar-top'); ?>
                </div>
                <?php else : ?>
                <div class="sidebar-widget ad-widget">
                    <div class="ad-placeholder" style="width: 300px; height: 250px;">
                        <p><?php _e('Advertisement', 'ihowz-theme'); ?><br>300x250</p>
                    </div>
                </div>
                <?php endif; ?>

                <!-- Related Articles -->
                <div class="sidebar-widget related-widget">
                    <h3><?php _e('Related Articles', 'ihowz-theme'); ?></h3>
                    <?php
                    $related_posts = new WP_Query(array(
                        'posts_per_page' => 3,
                        'post__not_in' => array(get_the_ID()),
                        'orderby' => 'rand'
                    ));

                    if ($related_posts->have_posts()) :
                        echo '<ul class="related-articles-list">';
                        while ($related_posts->have_posts()) : $related_posts->the_post();
                            echo '<li><a href="' . get_permalink() . '">' . get_the_title() . '</a></li>';
                        endwhile;
                        echo '</ul>';
                        wp_reset_postdata();
                    endif;
                    ?>
                </div>

                <!-- Quick Contact -->
                <div class="sidebar-widget contact-widget">
                    <h3><?php _e('Need Help?', 'ihowz-theme'); ?></h3>
                    <p><?php _e('Contact our expert team for personalized support.', 'ihowz-theme'); ?></p>
                    <a href="<?php echo esc_url(get_permalink(get_page_by_path('contact'))); ?>" class="btn btn-primary"><?php _e('Get Support', 'ihowz-theme'); ?></a>
                </div>

                <!-- Newsletter Signup -->
                <div class="sidebar-widget newsletter-widget">
                    <h3><?php _e('Stay Updated', 'ihowz-theme'); ?></h3>
                    <p><?php _e('Get the latest news and insights delivered to your inbox.', 'ihowz-theme'); ?></p>
                    <?php echo do_shortcode('[newsletter_form]'); ?>
                </div>
            </aside>

        </div>
    </div>

    <!-- Related Content Recommendations -->
    <section class="related-content-section">
        <div class="container">
            <h2><?php _e('You Might Also Like', 'ihowz-theme'); ?></h2>
            <div class="related-content-grid">
                <?php
                $recommended_posts = new WP_Query(array(
                    'posts_per_page' => 3,
                    'post__not_in' => array(get_the_ID()),
                    'orderby' => 'date',
                    'order' => 'DESC'
                ));

                if ($recommended_posts->have_posts()) :
                    while ($recommended_posts->have_posts()) : $recommended_posts->the_post();
                        ?>
                        <article class="recommended-post-card">
                            <?php if (has_post_thumbnail()) : ?>
                            <div class="post-thumbnail">
                                <?php the_post_thumbnail('medium'); ?>
                            </div>
                            <?php endif; ?>
                            <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                            <p><?php echo wp_trim_words(get_the_excerpt(), 20); ?></p>
                            <a href="<?php the_permalink(); ?>" class="read-more"><?php _e('Read More', 'ihowz-theme'); ?> &rarr;</a>
                        </article>
                        <?php
                    endwhile;
                    wp_reset_postdata();
                endif;
                ?>
            </div>
        </div>
    </section>

    <!-- Relevant Sponsor Content -->
    <section class="sponsor-content-section">
        <div class="container">
            <h2><?php _e('Relevant Services', 'ihowz-theme'); ?></h2>
            <div class="sponsor-content-grid">
                <?php if (is_active_sidebar('article-sponsors')) : ?>
                    <?php dynamic_sidebar('article-sponsors'); ?>
                <?php else : ?>
                    <!-- Placeholder sponsor content -->
                    <?php for ($i = 1; $i <= 2; $i++) : ?>
                    <div class="sponsor-content-card">
                        <div class="sponsor-ad-space" style="width: 100%; height: 250px;">
                            <p><?php echo sprintf(__('Sponsor Solution %d', 'ihowz-theme'), $i); ?><br>Related Service</p>
                        </div>
                    </div>
                    <?php endfor; ?>
                <?php endif; ?>
            </div>
        </div>
    </section>

</main>

<?php get_footer(); ?>
